### ISSUE TITLE
How could I use several breadcrumbs on page?

### ISSUE THREAD

**Issue by bocharsky-bw** [whiteoctober/BreadcrumbsBundle#46]
There are any solution to use a few different breadcumbs on the same page - main breadcrumbs and for sub block one?

**Comment by richsage** [comment]
Great idea! There's nothing that supports that presently - maybe some kind of namespace would work? eg:

    $breadcrumbs->getNamespace("main")->addBreadcrumb(...);

or

    $breadcrumbs->addNamespaceItem("main", $txt, $url);

with a default namespace of some kind. I'm open to suggestions :-)

**Comment by bocharsky-bw** [comment]
@richsage Thanks for quick reply!

I like first case, because with second case it's look like we need to add 2 methods: `addNamespaceItem` and `addNamespaceRouteItem` and it will be a bit awkwardly as for me.

I also considered to implement a `factory` pattern for this or it will be too complex? What do you think?

**Comment by richsage** [comment]
OK, I can do the first one. So, we can assume that `$breadcrumbs->addBreadcrumb()` uses the default namespace, and then if namespaces are required then the separate `getNamespace` method needs to be called? Maybe the standalone `addBreadcrumb` method then needs to be deprecated so as to force namespace usage in the future?

What did you have in mind for the factory pattern? I suspect as you say that it might be a bit complex, but interested to see your approach.

**Comment by bocharsky-bw** [comment]
I considered [KnpMenuBundle](http://symfony.com/doc/master/bundles/KnpMenuBundle/index.html) solution to build a few menus from factory service. In [Menu as a service](http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_service.html) described how to use  factory method to build menus. For example, in order to breadcumbs:
``` yaml
services:
    app.breadcrumbs.builder:
        class: App\Breadcrumbs\Builder
        arguments: ["@wo.breadcrumbs.builder"]
        # where "@wo.breadcrumbs.builder" is a core breadcrumbs service from WhiteOctoberBreadcrumbsBundle

    app.breadcrumbs.main:
        class: App\Breadcrumbs\MainBreadcrumbs
        factory_service: wo.breadcrumbs.builder
        factory_method: createMainBreadcrumbs
        arguments: []
        tags:
            - { name: wo_breadcrumbs, alias: main_breadcrumbs }

    app.breadcrumbs.sub_breadcrumb:
        class: App\Breadcrumbs\SubBreadcrumbs
        factory_service: wo.breadcrumbs.builder
        factory_method: createSubBreadcrumbs
        arguments: []
        tags:
            - { name: wo_breadcrumbs, alias: sub_breadcrumbs }
```

Also we can add default crumbs to it, for example, when I create `main_breadcrumbs` breadcrumbs it already should contain home crumb (we avoid to add home crumb at every action).

I thinks this could entail BC, but we can avoid it to add a new twig function to render breadcrumbs from factory.

@richsage What do you think?
